sudo: required
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/^untagged-.*$/"
  - "/^master-snapshot.*$/"
env:
  global:
  - LOCAL_JMX=no
  - TEST=""
  matrix:
  - TEST_TYPE=ccm CASSANDRA_VERSION=2.1.19
  - TEST_TYPE=ccm CASSANDRA_VERSION=2.1.19 GRIM_MIN=2 GRIM_MAX=2
  - TEST_TYPE=ccm CASSANDRA_VERSION=2.1.19 GRIM_MIN=2 GRIM_MAX=4
  - TEST_TYPE=ccm CASSANDRA_VERSION=2.2.11 GRIM_MIN=1 GRIM_MAX=1
  - TEST_TYPE=ccm CASSANDRA_VERSION=2.2.11 GRIM_MIN=2 GRIM_MAX=2
  - TEST_TYPE=ccm CASSANDRA_VERSION=2.2.11 GRIM_MIN=2 GRIM_MAX=4
  - TEST_TYPE=ccm CASSANDRA_VERSION=3.0.15 GRIM_MIN=1 GRIM_MAX=1
  - TEST_TYPE=ccm CASSANDRA_VERSION=3.0.15 GRIM_MIN=2 GRIM_MAX=2
  - TEST_TYPE=ccm CASSANDRA_VERSION=3.0.15 GRIM_MIN=2 GRIM_MAX=4
  - TEST_TYPE=ccm CASSANDRA_VERSION=3.11.1 GRIM_MIN=1 GRIM_MAX=1
  - TEST_TYPE=ccm CASSANDRA_VERSION=3.11.1 GRIM_MIN=2 GRIM_MAX=2
  - TEST_TYPE=ccm CASSANDRA_VERSION=3.11.1 GRIM_MIN=2 GRIM_MAX=4
  - TEST_TYPE=docker
matrix:
  fast_finish: true
  allow_failures:
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=2.2.10 GRIM_MIN=2 GRIM_MAX=2
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=2.2.10 GRIM_MIN=2 GRIM_MAX=4
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=3.0.15 GRIM_MIN=2 GRIM_MAX=2
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=3.0.15 GRIM_MIN=2 GRIM_MAX=4
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=3.11.1 GRIM_MIN=2 GRIM_MAX=4
  - env: TEST_TYPE=docker
services:
- postgresql
- docker
before_install: "./src/ci/before_install.sh"
install: "./src/ci/install.sh"
before_script: "./src/ci/before_script.sh"
script: "./src/ci/script.sh"
after_success: "./src/ci/after_success.sh"
after_failure: "./src/ci/after_failure.sh"
before_deploy: "./src/ci/before_deploy.sh"
deploy:
- provider: releases
  edge:
    branch: v1.8.47
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
  - src/packages/cassandra-reaper-${TRAVIS_TAG}-release.tar.gz
  - src/packages/reaper-*-1.x86_64.rpm
  - src/packages/reaper_*_amd64.deb
  skip_cleanup: true
  on:
    tags: true
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-rpm-beta.json
  user: adejanovski
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    branch: master
    condition: $CASSANDRA_VERSION = "2.1.19" &&  "x${GRIM_MIN}" = "x"
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-deb-beta.json
  user: adejanovski
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    branch: master
    condition: $CASSANDRA_VERSION = "2.1.19" &&  "x${GRIM_MIN}" = "x"
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-tarball-beta.json
  user: adejanovski
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    branch: master
    condition: $CASSANDRA_VERSION = "2.1.19" &&  "x${GRIM_MIN}" = "x"
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-maven-snapshot.json
  user: adejanovski
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    branch: master
    condition: $CASSANDRA_VERSION = "2.1.19" &&  "x${GRIM_MIN}" = "x"
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-rpm.json
  user: adejanovski
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    tags: true
    condition: $CASSANDRA_VERSION = "2.1.19" &&  "x${GRIM_MIN}" = "x"
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-deb.json
  user: adejanovski
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    tags: true
    condition: $CASSANDRA_VERSION = "2.1.19" &&  "x${GRIM_MIN}" = "x"
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-tarball.json
  user: adejanovski
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    tags: true
    condition: $CASSANDRA_VERSION = "2.1.19" &&  "x${GRIM_MIN}" = "x"
- provider: bintray
  edge:
    branch: v1.8.47
  file: src/ci/descriptor-maven.json
  user: adejanovski
  key: $BINTRAY_API_KEY
  dry-run: false
  skip_cleanup: true
  on:
    tags: true
    condition: $CASSANDRA_VERSION = "2.1.19" &&  "x${GRIM_MIN}" = "x"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/00ad453df6ac8ac0d0ba
    on_success: change
    on_failure: always
    on_start: never
