sudo: required
language: java
jdk:
  - oraclejdk8

env:
  global:
    - LOCAL_JMX=no
    - TEST=""
  matrix:
      # 2.1.18 runs all tests together because it's also for sonar reporting, see below
    - TEST_TYPE=ccm CASSANDRA_VERSION=2.1.18
#    - TEST_TYPE=ccm CASSANDRA_VERSION=2.1.18 GRIM_MIN=2 GRIM_MAX=2
#    - TEST_TYPE=ccm CASSANDRA_VERSION=2.1.18 GRIM_MIN=2 GRIM_MAX=4
#    - TEST_TYPE=ccm CASSANDRA_VERSION=2.2.10 GRIM_MIN=1 GRIM_MAX=1
#    - TEST_TYPE=ccm CASSANDRA_VERSION=2.2.10 GRIM_MIN=2 GRIM_MAX=2
#    - TEST_TYPE=ccm CASSANDRA_VERSION=2.2.10 GRIM_MIN=2 GRIM_MAX=4
#    - TEST_TYPE=ccm CASSANDRA_VERSION=3.0.10 GRIM_MIN=1 GRIM_MAX=1
#    - TEST_TYPE=ccm CASSANDRA_VERSION=3.0.14 GRIM_MIN=2 GRIM_MAX=2
#    - TEST_TYPE=ccm CASSANDRA_VERSION=3.0.14 GRIM_MIN=2 GRIM_MAX=4
#    - TEST_TYPE=ccm CASSANDRA_VERSION=3.11.0 GRIM_MIN=1 GRIM_MAX=1
#    - TEST_TYPE=ccm CASSANDRA_VERSION=3.11.0 GRIM_MIN=2 GRIM_MAX=2
#    - TEST_TYPE=ccm CASSANDRA_VERSION=3.11.0 GRIM_MIN=2 GRIM_MAX=4
    - TEST_TYPE=docker

matrix:
  fast_finish: true
  allow_failures:
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=2.2.10 GRIM_MIN=2 GRIM_MAX=2
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=2.2.10 GRIM_MIN=2 GRIM_MAX=4
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=3.0.14 GRIM_MIN=2 GRIM_MAX=2
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=3.0.14 GRIM_MIN=2 GRIM_MAX=4
  - env: TEST_TYPE=ccm CASSANDRA_VERSION=3.11.0 GRIM_MIN=2 GRIM_MAX=4

services:
  - postgresql
  - docker

before_install: ./src/ci/before_install.sh

install: ./src/ci/install.sh

before_script: ./src/ci/before_script.sh

script: ./src/ci/script.sh

after_success: ./src/ci/after_success.sh

after_failure: ./src/ci/after_failure.sh

before_deploy: ./src/ci/before_deploy.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "cassandra-reaper-${TRAVIS_TAG}-release.tar.gz"
    - "src/packages/reaper-*-1.x86_64.rpm"
    - "src/packages/reaper_*_amd64.deb"
  skip_cleanup: true
  on:
    tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/00ad453df6ac8ac0d0ba
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
